#!/usr/bin/env python3

import sys
from math import *

import rospy
import actionlib
from actionlib_msgs.msg import GoalStatus

from geometry_msgs.msg import Point, PoseStamped

from spar_msgs.msg import FlightMotionAction, FlightMotionGoal

from std_msgs.msg import Bool, UInt8


# Make some space to record down ROI
roi_location = PoseStamped()


def pub_roi():
    pub = rospy.Publisher('roi', PoseStamped, queue_size=10)
    rospy.init_node('pub_roi', anonymous=True)
    roi_location.pose.position.x = 2.0
    roi_location.pose.position.y = 2.0
    roi_location.pose.position.z = 2.0
    pub.publish(roi_location)
  
if __name__ == '__main__':
    try:
        pub_roi()
    except rospy.ROSInterruptException:
        pass